<?php

declare(strict_types=1);

require_once "config.php";

$init = <<<SQL
CREATE TABLE IF NOT EXISTS user (
	id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
	username VARCHAR(21) UNIQUE NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS cd (
	id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
	title VARCHAR(255) NOT NULL,
	label VARCHAR(255) NOT NULL,
	year SMALLINT(4) NOT NULL, -- lol year 32768 problem
	artist VARCHAR(255) NOT NULL,
	price DECIMAL(10,2) NOT NULL
);
CREATE TABLE IF NOT EXISTS track (
	id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
	name VARCHAR(255) NOT NULL,
	trackNumber SMALLINT(4) NOT NULL,
	duration TIME NOT NULL,
	cdId VARCHAR(36) NOT NULL,
	FOREIGN KEY (cdId) REFERENCES cd(id) ON DELETE CASCADE
);
SQL;

$DB = new PDO("mysql:host={$CONFIG["DB_HOST"]};dbname={$CONFIG["DB_NAME"]}", $CONFIG["DB_USER"], $CONFIG["DB_PASSWORD"], [
	PDO\Mysql::ATTR_INIT_COMMAND => $init,
	PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
]);
